### ISSUE TITLE
admin/grades tab

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classportal-ui-next#2]
@stecler if you can make `AdminController::adminGradesPage` retrieve the grades for 310, I'll work on the rendering to get that to work correctly.

**Comment by andrewstec** [comment]
@rtholmes Just to confirm, I am currently on it.

**Comment by rtholmes** [comment]
Great @stecler . Let me know when there's data to render; I wonder if maybe something isn't right in the `AdminController` because right now it is definitely an empty array coming back for the query:

```
App.ts:135 App::init()::show - page: adminGradesPage
10:58:18.677 AdminController.ts:62 AdminController::adminGradesPage - start
10:58:18.678 Network.ts:11 Network::handleRemote( https://localhost:5000/310/admin/grades ) - start
10:58:18.705 Network.ts:22 Network::handleRemote() 200 return
10:58:18.706 GradeView.ts:19 GradeView::render(..) - start
10:58:18.707 GradeView.ts:22 GradeView::render(..) - data: {"response":[]}
```

**Comment by rtholmes** [comment]
Implemented.
